version: '3.0'

services:
  team1_ansible:
    image: ubuntu-ansible-sshd:latest
    container_name: team1_ansible
    restart: unless-stopped
    ports:
      - "2201:22"
    stdin_open: true
    tty: true
    environment:
      SSH_USERNAME: ansible
      PASSWORD: Ansible12!
  team2_ansible:
    image: ubuntu-ansible-sshd:latest
    container_name: team2_ansible
    restart: unless-stopped
    ports:
      - "2202:22"
    stdin_open: true
    tty: true
    environment:
      SSH_USERNAME: ansible
      PASSWORD: Ansible12!
